### ISSUE TITLE
几点建议，能否实现一下？

### ISSUE THREAD

**Issue by bingdu0** [LJYcoder/DevRing#1]
1.支持cookie
2.多文件带进度条的下载
3.网络请求耗时较长，弹一个ProgressDialog

**Comment by LJYcoder** [comment]
最近工作比较忙，过段时间有空了我尝试优化下，谢谢你的建议~

**Comment by LJYcoder** [comment]
最近刚离职正在优化这个项目，计划3月底或4月初将推出改版，到时会加入下载例子。
