### ISSUE TITLE
jcenter怎么获取呢

### ISSUE THREAD

**Issue by ichtj** [LJYcoder/DevRing#10]
![image](https://user-images.githubusercontent.com/31207253/48172405-bb9c6f80-e33a-11e8-913e-e92c089ccbf4.png)
请问一下这个版本怎么获取的呢  我想获取仓库的版本，但是不知道怎么弄

**Comment by LJYcoder** [comment]
没听懂什么意思。。

**Comment by ichtj** [comment]
就是这些version license 版本怎么获取的 是要引用什么网址的参数吗 我有有一个库想试一下 但是不知道怎么弄

**Comment by LJYcoder** [comment]
版本号是自己手敲的，这里是四张图片来的，至于图片可以用这个网站生成https://shields.io/#/。
生成后写进README.md里就行了，具体你到md文件里看吧
