### ISSUE TITLE
EventBus中的问题

### ISSUE THREAD

**Issue by vistar1986** [LJYcoder/DevRing#13]
你好，DevRing框架中发现一个问题，如果使用自定义的BusManager 会出现发送一次事件多次执行的问题，原因是在Onstart中注册EventBus导致的

**Comment by LJYcoder** [comment]
为什么认为是在onStart中注册导致的

**Comment by LJYcoder** [comment]
如果使用自定义的BusManager，请注意：
在重写注册方法时，请先判断是否已注册过，已注册过则不要进行重复注册操作，
因为我把注册操作放在了onStart中执行（为了兼容EventBus的粘性事件），在页面来回切换时会不止一次回调onStart方法，所以重复注册的话可能会导致发送一次事件收到多次回调的情况。
