### ISSUE TITLE
代码中的一个小错误

### ISSUE THREAD

**Issue by a765032380** [LJYcoder/DevRing#3]
UploadActivity 类中的154行需要把READ_EXTERNAL_STORAGE改为WRITE_EXTERNAL_STORAGE，写的权限包括读的权限。如果没有写的权限，我在安卓7.0的情况下APP会崩溃。很不错的代码，谢谢分享，如果首页的两个Fragment加入到ViewPager中就更好了，并对指示条进行自定义。纯属个人建议。

**Comment by LJYcoder** [comment]
请问下你有没修改项目的targetSdkVersion？ 
我记得动态权限申请中，只要某个权限授予了，那么与它在同一个权限组里的其他权限都会自动授权。

**Comment by a765032380** [comment]
targetSdkVersion我设置为了27，按照你的代码，只申请了读的权限，没有写的权限。

**Comment by LJYcoder** [comment]
好的，另外想了解下你是用什么手机测的？
至于ViewPager的那个我就不修改了，因为demo的重点在于演示开发库的使用。
谢谢你的反馈~

**Comment by a765032380** [comment]
我用虚拟机测试的。。。API27的虚拟机，你也可以试一下。

**Comment by LJYcoder** [comment]
恩，确实崩了。
查了下资料，8.0之后规则有所改动：某个权限授予后，与它在同一个权限组里的其他权限并不会自动授权。https://blog.csdn.net/yanzhenjie1003/article/details/76719487
