### ISSUE TITLE
网络请求如何进行链式调度

### ISSUE THREAD

**Issue by Lee-Jian** [LJYcoder/DevRing#5]
public void commonRequest(Observable observable, Observer observer, LifecycleTransformer transformer) {
        handleRetry(handleThread(handleLife(observable, transformer)), mHttpConfig.isUseRetryWhenError(), mHttpConfig.getTimeRetryDelay(), mHttpConfig.getMaxRetryCount()).subscribe
                (observer);
    }
这里进行了订阅，那么如何进行链式调度，如注册后直接登录

**Comment by LJYcoder** [comment]
你是指注册请求成功后直接调用登录请求吗？
如果是这样的话，可以使用flatMap操作符将注册和登录合成一个Observable，然后通过commomRequest方法进行请求，参考我那篇Retrofit+RxJava博客中“使用"的嵌套请求
