### ISSUE TITLE
网络配置该如何进行定制

### ISSUE THREAD

**Issue by Lee-Jian** [LJYcoder/DevRing#6]
DevRing.configureHttp()//配置retrofit
                .setBaseUrl(UrlConstants.BASE_URL)//设置BaseUrl
                .setConnectTimeout(15)//设置请求超时时长，单位秒
//                .setMapHeader(mapHeader)//设置全局的header信息
//                .setIsUseCache(true)//设置是否启用缓存，默认不启用
//                .setCacheFolder(file)//设置缓存地址，传入的file需为文件夹，默认保存在/storage/emulated/0/Android/data/com.xxx.xxx/cache/retrofit_http_cache下
//                .setCacheSize(size)//设置缓存大小，单位byte，默认20M
//                .setCacheTimeWithNet(time)//设置有网络时缓存保留时长，单位秒，默认60秒
//                .setCacheTimeWithoutNet(time)//设置无网络时缓存保留时长，单位秒，默认一周
//                .setIsUseRetryWhenError(true)//设置是否开启失败重试功能，目前仅支持普通的网络请求，上传下载不支持。默认不开启
//                .setMaxRetryCount(2)//设置失败后重试的最大次数，默认3次
//                .setTimeRetryDelay(5)//设置失败后重试的延迟时长，单位秒，默认3秒
                .setIsUseLog(true);//设置是否开启Log，默认不开启
        //如果提供的配置方法还无法满足你的需求，那可以通过以下方法获取builder进行你的定制
        ClearableCookieJar cookieJars = new PersistentCookieJar(new SetCookieCache(), new SharedPrefsCookiePersistor(getApplicationContext()));

        HttpLoggingInterceptor loggingInterceptor = new HttpLoggingInterceptor();
        loggingInterceptor.setLevel(HttpLoggingInterceptor.Level.BODY);

        OkHttpClient okHttpClient =
                DevRing.configureHttp().getOkHttpClientBuilder()
                        .connectTimeout(10000L, TimeUnit.MILLISECONDS)
                        .readTimeout(10000L, TimeUnit.MILLISECONDS)
                        .addInterceptor(loggingInterceptor)
                        .cookieJar(cookieJars)
                        .build();
        DevRing.configureHttp().getRetrofitBuilder()
                .baseUrl(UrlConstants.BASE_URL)
                .addConverterFactory(GsonConverterFactory.create())
                .addCallAdapterFactory(RxJava2CallAdapterFactory.create())
                .client(okHttpClient)
                .build();
这样定制对吗？cookieJar没有生效啊

**Comment by LJYcoder** [comment]
恩，我刚刚看了下代码，是有点问题，我有空的时候改一下发个新版。到时候你按下面代码试试（不需要build，然后readTimeout和cookieJar以外的属性都可以通过我提供的api设置）：
DevRing.configureHttp().getOkHttpClientBuilder()
            .readTimeout(10000L, TimeUnit.MILLISECONDS)
            .cookieJar(cookieJars);

**Comment by LJYcoder** [comment]
修改过来了，使用目前最新的1.0.15版本试试。
