### ISSUE TITLE
一个bug,上传下载失败时是在子线程,这里应该用handle.post()

### ISSUE THREAD

**Issue by o03150** [LJYcoder/DevRing#8]

**Comment by LJYcoder** [comment]
请求回调是在主线程的，不管成功还是失败

**Comment by o03150** [comment]
调用是主线程调用没错,但是读取数据可是在子线程,,这里如果读取数据错误,比如我把网断了,这里抛出异常,代码里捕获了,此时还是在子线程,然后回调给主线程toast,这里是UI,所以提示了"Only the original thread that created a view hierarchy can touch its views."

**Comment by o03150** [comment]
![rev](https://user-images.githubusercontent.com/20020827/45213182-62c44280-b2c9-11e8-8f98-9eb2e94442c6.png)

**Comment by LJYcoder** [comment]
好的，我去改下，谢谢提醒~
