### ISSUE TITLE
一键生成DevRing快速模板 AS会报错

### ISSUE THREAD

**Issue by Lyansun** [LJYcoder/DevRing#9]
如题

**Comment by LJYcoder** [comment]
具体报什么错呢？提供下截图吧，我这边一直在用，没出问题

**Comment by xbo1376** [comment]
如果是包结构的问题，那么需要注意要在根包下创建，也就是 manifest 声明的那个包名下。比如包名是com.tes.one，那么创建时就在这个包下创建，不要在 com.tes.one.mvp.view.activity 下创建。

**Comment by sddxl2** [comment]
请问下一键生成DevRing快速模板的连接地址在哪啊

**Comment by LJYcoder** [comment]
https://github.com/LJYcoder/MvpDagger
